"""add is_admin to users

Revision ID: 0279c3a6d96e
Revises: 30f12a1c1a62
Create Date: 2026-06-28 20:49:57.189635
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0279c3a6d96e'
down_revision: Union[str, None] = '30f12a1c1a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
